### ISSUE TITLE
xcb_utf8_to_compound_text() fails on the '–' and '–' characters

### ISSUE THREAD

**Issue by hckiang** [fcitx/xcb-imdkit#5]
When a UTF8 string contains `'–' (0xe2 0x80 0x93)` or `'–' (0xe2 0x80 0x94)`, `xcb_utf8_to_compound_text()` will return NULL. It shouldn't be. Any idea where is the bug originated from? Are there quick workarounds?

Example text:
—？…！：；。，、

**Comment by wengxt** [comment]
Indeed. I guess the problem is because TATAR-CYR is picked up by encoding but it is not defined in lcCT.c . I don't know why this is the case because if same happens, libX11 would have the same trouble. But at least libX11 has some "preferred" encoding which make resolve this problem as a side effect. Since utf8 already cover everything.. maybe when we encoding the string we should always use utf8 so the problem could be avoided.
